### ISSUE TITLE
Cannot identify subparts of chorus and repeating "Other" sections

### ISSUE THREAD

**Issue by sebastian-adam** [beantowel/chorus-from-music-structure#3]
Hi, this project is amazing. I've used `pychorus` previously and am most excited about the improved segmentation your work offers.

The issue I'm facing is that when I run `python3 predict.py ./data/example/starfall.mp3`, I don't receive nearly as much segmentation as is shown in your example screenshot.

My initial thought is that there are configuration variables that I need to alter, but I've had no luck finding them yet.

For example, the predicted segmentation looks like the following when using `Huawei_Dataset` and is very similar when using `RWC_Popular_Dataset` or `CCM_Dataset`:
```
0.00	65.14	others
65.14	84.72	chorus
84.72	132.15	others
132.15	149.40	chorus
149.40	159.47	others
159.47	175.88	chorus
175.88	191.05	others
```

 The UI then looks as follows:
![Screen Shot 2023-02-01 at 1 43 01 PM](https://user-images.githubusercontent.com/19532408/216149507-85369e21-87fd-4135-b5f8-974708816d39.png)

And what I'm hoping to achieve is something closer to this, with `Chorus A`, `Chorus B`, etc as well as `Other A`, `Other B`, etc:
![Screen Shot 2023-02-01 at 1 55 51 PM](https://user-images.githubusercontent.com/19532408/216149578-15a40ac5-eaa2-4df4-a1ac-61ee5847a171.png)

If it's not a configuration issue, I'm happy to provide my environment metadata, packages I've upgraded to get it running, and the attempts to get it working I've tried so far. I've been banging my head for three days now and thought I'd finally reach out.

Thanks for sharing your work.

**Comment by beantowel** [comment]
Working with Python dependencies on Windows is really a nightmare!!
After some investigation, I remembered the small segmentation it's not configurable. To get there, you should:
- use seqRecur algorithm like: ` python predict.py ./data/example/starfall.mp3 --force false --algo seqRecur`
- comment out `removeNumber` lines in `predict.py`
```python
        # write output and viewer metadata
        # if algo not in ["single", "multi"]:
        #     mirexFmt = predictor(ddataset, i)
        #     mirexFmt = removeNumber(mirexFmt)
        #     mirexFmt = mergeIntervals(mirexFmt)
```

**Comment by sebastian-adam** [comment]
Not only does this work, but the output is so impressive. Thanks for the quick reply; I was stuck and now I won't lose momentum. Issue is resolved. Hope you are doing well in all your current projects.
